# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: format
      - task: test
      - task: build

  build:
    desc: Builds the project
    cmds:
      - roc build
    sources:
      - main.roc
    generates:
      - main

  format:
    desc: Formats roc files
    cmds:
      - roc format main.roc
    sources:
      - main.roc

  test:
    desc: Runs checks and tests
    cmds:
      - roc format --check main.roc
      - roc check
      - roc test
    sources:
      - main.roc

  run-server:
    desc: Runs the webserver
    deps:
      - build
    cmds:
      - ./main

  get-roc:
    desc: Downloads the latest nightly build of roc and unzips it
    cmds:
      - wget https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-linux_x86_64-latest.tar.gz --no-verbose --output-document roc.tar.gz
      - tar -xf roc.tar.gz
      - rm roc.tar.gz
      - mv "$(pwd)/$(find . -type d -iname 'roc_nightly*' | head -n 1)" roc-dir
